name: back_to_monke
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_ipfs: ^0.0.2
  dio: ^4.0.6
  image_picker_web: ^2.1.1
  animated_text_kit: ^4.2.1
  animations: ^2.0.3
  animated_text: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  glassmorphism_ui: ^0.2.0
  flutter_native_splash: ^2.2.1

flutter_native_splash:
  color: "#000000"
  image: assets/images/splash_image.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/
    -
  fonts:
    - family: SFUIDisplay
      fonts:
        - asset: assets/fonts/SFUIDisplay-Bold.ttf
        - asset: assets/fonts/SFUIDisplay-Regular.otf
        - asset: assets/fonts/SFUIDisplay-Heavy.otf